// 自定义音乐映射配置
// 格式: 代码 -> {name: 文件名, path: 文件路径, note: 备注 type: bgm/se, index: 曲目索引, volume: 音量(可选，默认1.0)}
// 这个文件会在页面加载时自动覆盖默认配置

// 如果你想修改配置，只需要编辑这个文件
// 代码会自动检测并使用这里的配置
// 可以添加不存在的代码作为背景音乐或者音效

// 示例：使用 name 字段指定变量名
// ["81", { name: "myCustomMusicData", path: "music/custom.js", index: 0, note: "自定义音乐示例", type: "bgm" , volume: 0.8 }],

window.musicConfig = new Map([
		//这部分是音效
	["03", { path: "music/ct2_def.js", index: 0x28, note: "", type: "se" }],
	["04", { path: "music/ct2_def.js", index: 0x29, note: "", type: "se" }],
	["05", { path: "music/ct2_def.js", index: 0x2A, note: "", type: "se" }],
	["06", { path: "music/ct2_def.js", index: 0x2B, note: "", type: "se" }],
	["07", { path: "music/ct2_def.js", index: 0x2C, note: "", type: "se" }],
	["08", { path: "music/ct2_def.js", index: 0x2D, note: "", type: "se" }],
	["09", { path: "music/ct2_def.js", index: 0x2E, note: "", type: "se" }],
	["0A", { path: "music/ct2_def.js", index: 0x2F, note: "", type: "se" }],
	["0B", { path: "music/ct2_def.js", index: 0x30, note: "", type: "se" }],
	["0C", { path: "music/ct2_def.js", index: 0x31, note: "", type: "se" }],
	["0D", { path: "music/ct2_def.js", index: 0x32, note: "", type: "se" }],
	["0E", { path: "music/ct2_def.js", index: 0x33, note: "", type: "se" }],
	["0F", { path: "music/ct2_def.js", index: 0x34, note: "", type: "se" }],
	["10", { path: "music/ct2_def.js", index: 0x35, note: "", type: "se" }],
	["11", { path: "music/ct2_def.js", index: 0x36, note: "", type: "se" }],
	["12", { path: "music/ct2_def.js", index: 0x37, note: "", type: "se" }],
	["13", { path: "music/ct2_def.js", index: 0x38, note: "", type: "se" }],
	["14", { path: "music/ct2_def.js", index: 0x39, note: "", type: "se" }],
	["15", { path: "music/ct2_def.js", index: 0x3A, note: "", type: "se" }],
	["16", { path: "music/ct2_def.js", index: 0x3B, note: "", type: "se" }],
	["17", { path: "music/ct2_def.js", index: 0x3C, note: "", type: "se" }],
	["18", { path: "music/ct2_def.js", index: 0x3D, note: "", type: "se" }],
	["19", { path: "music/ct2_def.js", index: 0x3E, note: "", type: "se" }],
	["1A", { path: "music/ct2_def.js", index: 0x3F, note: "", type: "se" }],
	["1B", { path: "music/ct2_def.js", index: 0x40, note: "", type: "se" }],
	["1C", { path: "music/ct2_def.js", index: 0x41, note: "", type: "se" }],
	["1D", { path: "music/ct2_def.js", index: 0x42, note: "", type: "se" }],
	["1E", { path: "music/ct2_def.js", index: 0x43, note: "", type: "se" }],
	["1F", { path: "music/ct2_def.js", index: 0x44, note: "", type: "se" }],
	["20", { path: "music/ct2_def.js", index: 0x45, note: "", type: "se" }],
	//["21", { path: "music/ct2_def.js", index: 0, note: "0x01BFC4_21",type:"se" }],//未知作用，应该是剧情火焰射门
	["22", { path: "music/ct2_def.js", index: 0x47, note: "", type: "se" }],
	["23", { path: "music/ct2_def.js", index: 0x48, note: "", type: "se" }],
	["24", { path: "music/ct2_def.js", index: 0x49, note: "", type: "se" }],
	["25", { path: "music/ct2_def.js", index: 0x4A, note: "", type: "se" }],
	["26", { path: "music/ct2_def.js", index: 0x4B, note: "", type: "se" }],
	["27", { path: "music/ct2_def.js", index: 0x4C, note: "", type: "se" }],
	["28", { path: "music/ct2_def.js", index: 0x4D, note: "", type: "se" }],
	["29", { path: "music/ct2_def.js", index: 0x4E, note: "", type: "se" }],
	["2A", { path: "music/ct2_def.js", index: 0x4F, note: "", type: "se" }],
	["2B", { path: "music/ct2_def.js", index: 0x50, note: "", type: "se" }],
	["2C", { path: "music/ct2_def.js", index: 0x51, note: "", type: "se" }],
	["2D", { path: "music/ct2_def.js", index: 0x52, note: "", type: "se" }],
	["2E", { path: "music/ct2_def.js", index: 0x53, note: "", type: "se" }],
	["2F", { path: "music/ct2_def.js", index: 0x54, note: "", type: "se" }],
	["30", { path: "music/ct2_def.js", index: 0x55, note: "", type: "se" }],
	//["31", { path: "music/ct2_def.js", index: 0xFF, note: "",type:"se" }],//空索引

	//以下是背景音乐
	["32", { path: "music/ct2_def.js", index: 0, note: "比赛5分钟倒计时音乐，最后关头（22）",type:"bgm" }],
	["33", { path: "music/nsf_batch_merged.js",name: "Hockey", index: 2, note: "输入密码时的音乐，穿越未来（23）",type:"bgm" }],
	["34", { path: "music/ct2_def.js", index: 2, note: "日本高中联赛音乐，决战日本（7-11关）（35）",type:"bgm" }],
	["35", { path: "music/nsf_batch_merged.js",name: "samishiinet", index: 0, note: "巴西联赛音乐，巴西之战（1-5关）（34）",type:"bgm" , volume: 0.8}],
	["36", { path: "music/nsf_batch_merged.js",name: "Touhou_EoCA", index: 0, note: "法国音乐，埃菲尔攻击（38）",type:"bgm" }],
	["37", { path: "music/ct2_def.js", index: 5, note: "东邦音乐，猛虎压境（31）",type:"bgm" }],
	["38", { path: "music/ct2_def.js", index: 6, note: "德国音乐，震撼火焰（32）",type:"bgm" }],
	["39", { path: "music/ct2_def.js", index: 7, note: "南葛音乐，南葛的反击（28）",type:"bgm" }],
	["3A", { path: "music/ct2_def.js", index: 8, note: "亚洲突围音乐（37）",type:"bgm" }],
	["3B", { path: "music/nsf_batch_merged.js",name: "加纳战机_NTSC_62", index: 6, note: "邀请赛（13至16关）音乐（36）",type:"bgm" }],
	["3C", { path: "music/nsf_batch_merged.js",name: "Mega_Man_9_5_Aurora_Man_Stage", index: 0, note: "圣保罗音乐，足球是朋友（27）",type:"bgm" }],
	["3D", { path: "music/ct2_def.js", index: 11, note: "阿根廷音乐，草原雄鹰（39）",type:"bgm" }],
	["3E", { path: "music/nsf_batch_merged.js",name: "Counter_Strike_反恐精英", index: 0, note: "巴西音乐，神秘劲旅（33）",type:"bgm" }],
	["3F", { path: "music/nsf_batch_merged.js",name: "goal3", index: 5, note: "全日本音乐，全日本进行曲（29）",type:"bgm" }],
	["40", { path: "music/nsf_batch_merged.js",name: "达拉崩吧", index: 0, note: "弗拉门戈音乐，黄金之鹫（30）",type:"bgm" }],
	["41", { path: "music/ct2_def.js", index: 15, note: "我方进球音乐（24）",type:"bgm" }],
	["42", { path: "music/nsf_batch_merged.js",name: "NIGANMAAAAAAAA", index: 0, note: "对方进球音乐（25）",type:"bgm" }],
	["43", { path: "music/ct2_def.js", index: 17, note: "犯规音乐（26）",type:"bgm" }],
	["44", { path: "music/ct2_def.js", index: 18, note: "爆笑三人转会议音乐（21）",type:"bgm" }],
	["45", { path: "music/ct2_def.js", index: 19, note: "爆笑三人转开始音乐（01）",type:"bgm" }],
	["46", { path: "music/ct2_def.js", index: 20, note: "翼单挑曼昂尼剧情音乐（06）",type:"bgm" }],
	["47", { path: "music/ct2_def.js", index: 21, note: "南葛战胜东邦剧情音乐（05）",type:"bgm" }],
	["48", { path: "music/ct2_def.js", index: 22, note: "爆机翼与早苗对话剧情音乐（11）",type:"bgm" }],
	["49", { path: "music/ct2_def.js", index: 23, note: "曼昂尼接住旋转射门后剧情音乐（12）",type:"bgm" }],
	["4A", { path: "music/ct2_def.js", index: 0xFF, note: "停止播放声音",type:"bgm" }],
	["4B", { path: "music/ct2_def.js", index: 24, note: "翼领悟飓风射门的剧情音乐，暴风雨中的试炼（13）",type:"bgm" }],
	["4C", { path: "music/ct2_def.js", index: 25, note: "最后一关对巴西会议音乐，最后的激励（14）",type:"bgm" }],
	["4D", { path: "music/ct2_def.js", index: 26, note: "爆机音乐之一，详细参考原曲（15）",type:"bgm" }],
	["4E", { path: "music/ct2_def.js", index: 27, note: "翼举奖杯的爆机音乐（16）",type:"bgm" }],
	["4F", { path: "music/ct2_def.js", index: 28, note: "爆机音乐，详细参考（17）",type:"bgm" }],
	["50", { path: "music/ct2_def.js", index: 29, note: "早苗最后告别剧情音乐（18）",type:"bgm" }],
	["51", { path: "music/ct2_def.js", index: 30, note: "隐藏剧情中与罗伯特对话（02）",type:"bgm" }],
	["52", { path: "music/ct2_def.js", index: 31, note: "翼领悟旋转倒挂的短促音乐（07）",type:"bgm" }],
	["53", { path: "music/ct2_def.js", index: 32, note: "卡洛斯第一次露面剧情音乐（04）",type:"bgm" }],
	["54", { path: "music/ct2_def.js", index: 33, note: "库因布拉神秘亮相剧情音乐（08）",type:"bgm" }],
	["55", { path: "music/nsf_batch_merged.js",name: "加纳战机_NTSC_62", index: 19, note: "会议音乐（03）",type:"bgm" }],
	["56", { path: "music/ct2_def.js", index: 35, note: "比赛输了的音乐（20）",type:"bgm" }],
	["57", { path: "music/nsf_batch_merged.js",name: "数码宝贝_brave_heart", index: 0, note: "翼为曼昂尼所震撼的剧情音乐（09）",type:"bgm" }],
	["58", { path: "music/nsf_batch_merged.js",name: "goal3", index: 1, note: "片头音乐（00）",type:"bgm" , volume: 0.2}],
	["59", { path: "music/ct2_def.js", index: 38, note: "爆机音乐之一，详参（19）",type:"bgm" }],
	["5A", { path: "music/nsf_batch_merged.js",name: "年仅三岁的国王毫无畏惧", index: 0, note: "第一关赢后，卡洛斯的剧情音乐（10）",type:"bgm"	 }],

	//以下部分属于特殊音乐，自身播放时长比较短，但也属于背景音乐范围(部分为剧情音效)
	//["5B", { path: "music/ct2_def.js", index: 0xFF, note: "BUG音乐,也可以试听一下",type:"bgm" }],
	//["5C", { path: "music/ct2_def.js", index: 0, note: "无声音",type:"bgm" }],
	["5D", { path: "music/ct2_def.js", index: 0x56, note: "进球,网未穿56",type:"se" }],
	["5E", { path: "music/ct2_def.js", index: 0x57, note: "57",type:"se" }],
	["5F", { path: "music/ct2_def.js", index: 0x58, note: "58",type:"se" }],
	["60", { path: "music/ct2_def.js", index: 0x59, note: "进球,网未穿59",type:"se" }],
	["61", { path: "music/ct2_def.js", index: 0x5A, note: "进球,网射穿5A",type:"se" }],
	["62", { path: "music/ct2_def.js", index: 0x5B, note: "观众喝彩声5B",type:"se" }],
	["63", { path: "music/ct2_def.js", index: 0x5C, note: "球没进5C",type:"se" }],
	["64", { path: "music/ct2_def.js", index: 0x5D, note: "头球猛撞的一瞬间5D",type:"se" }],
	["65", { path: "music/ct2_def.js", index: 0x5E, note: "球爆裂的声音5E",type:"se" }],
	["66", { path: "music/ct2_def.js", index: 0x5F, note: "裁判的哨声5F",type:"se" }],
	["67", { path: "music/ct2_def.js", index: 0x60, note: "犯规哨声,后接26犯规音乐[这个在pm中没有]60",type:"bgm" }],
	["68", { path: "music/ct2_def.js", index: 0x61, note: "闪躲成功61",type:"se" }],
	["69", { path: "music/ct2_def.js", index: 0x62, note: "此起彼伏的喝彩声,比87略小声62",type:"se" }],
	["6A", { path: "music/ct2_def.js", index: 0x63, note: "机起飞的声音63",type:"se" }],
	["6B", { path: "music/ct2_def.js", index: 0x64, note: "剧情中施奈德火焰的前奏声音64",type:"se" }],
	["6C", { path: "music/ct2_def.js", index: 0x65, note: "对巴西赛前钟表到点的声音65",type:"se" }],
	["6D", { path: "music/ct2_def.js", index: 0x66, note: "这个声音既熟悉又陌生,故暂不解释66",type:"se" }],
	["6E", { path: "music/ct2_def.js", index: 0x67, note: "对巴西赛前钟表声音67",type:"se" }],
	["6F", { path: "music/ct2_def.js", index: 0x68, note: "人物升级的音乐68",type:"se" }],
	["70", { path: "music/ct2_def.js", index: 0x45, note: "下雨声45",type:"se" }],
	["71", { path: "music/ct2_def.js", index: 0x45, note: "下雨声45",type:"se" }],

	//自定义
	["80", { path: "music/nsf_batch_merged.js",name: "Ninja_Gaiden_II",index: 0x02, note: "bgm",type:"bgm" }],

]);





// 配置备份
musicConfigback = new Map([//复制下面的内容覆盖 替换上面的还原原始音乐
	//这部分是音效
	["03", { path: "music/ct2_def.js", index: 0x28, note: "", type: "se" }],
	["04", { path: "music/ct2_def.js", index: 0x29, note: "", type: "se" }],
	["05", { path: "music/ct2_def.js", index: 0x2A, note: "", type: "se" }],
	["06", { path: "music/ct2_def.js", index: 0x2B, note: "", type: "se" }],
	["07", { path: "music/ct2_def.js", index: 0x2C, note: "", type: "se" }],
	["08", { path: "music/ct2_def.js", index: 0x2D, note: "", type: "se" }],
	["09", { path: "music/ct2_def.js", index: 0x2E, note: "", type: "se" }],
	["0A", { path: "music/ct2_def.js", index: 0x2F, note: "", type: "se" }],
	["0B", { path: "music/ct2_def.js", index: 0x30, note: "", type: "se" }],
	["0C", { path: "music/ct2_def.js", index: 0x31, note: "", type: "se" }],
	["0D", { path: "music/ct2_def.js", index: 0x32, note: "", type: "se" }],
	["0E", { path: "music/ct2_def.js", index: 0x33, note: "", type: "se" }],
	["0F", { path: "music/ct2_def.js", index: 0x34, note: "", type: "se" }],
	["10", { path: "music/ct2_def.js", index: 0x35, note: "", type: "se" }],
	["11", { path: "music/ct2_def.js", index: 0x36, note: "", type: "se" }],
	["12", { path: "music/ct2_def.js", index: 0x37, note: "", type: "se" }],
	["13", { path: "music/ct2_def.js", index: 0x38, note: "", type: "se" }],
	["14", { path: "music/ct2_def.js", index: 0x39, note: "", type: "se" }],
	["15", { path: "music/ct2_def.js", index: 0x3A, note: "", type: "se" }],
	["16", { path: "music/ct2_def.js", index: 0x3B, note: "", type: "se" }],
	["17", { path: "music/ct2_def.js", index: 0x3C, note: "", type: "se" }],
	["18", { path: "music/ct2_def.js", index: 0x3D, note: "", type: "se" }],
	["19", { path: "music/ct2_def.js", index: 0x3E, note: "", type: "se" }],
	["1A", { path: "music/ct2_def.js", index: 0x3F, note: "", type: "se" }],
	["1B", { path: "music/ct2_def.js", index: 0x40, note: "", type: "se" }],
	["1C", { path: "music/ct2_def.js", index: 0x41, note: "", type: "se" }],
	["1D", { path: "music/ct2_def.js", index: 0x42, note: "", type: "se" }],
	["1E", { path: "music/ct2_def.js", index: 0x43, note: "", type: "se" }],
	["1F", { path: "music/ct2_def.js", index: 0x44, note: "", type: "se" }],
	["20", { path: "music/ct2_def.js", index: 0x45, note: "", type: "se" }],
	//["21", { path: "music/ct2_def.js", index: 0, note: "0x01BFC4_21",type:"se" }],//未知作用，应该是剧情火焰射门
	["22", { path: "music/ct2_def.js", index: 0x47, note: "", type: "se" }],
	["23", { path: "music/ct2_def.js", index: 0x48, note: "", type: "se" }],
	["24", { path: "music/ct2_def.js", index: 0x49, note: "", type: "se" }],
	["25", { path: "music/ct2_def.js", index: 0x4A, note: "", type: "se" }],
	["26", { path: "music/ct2_def.js", index: 0x4B, note: "", type: "se" }],
	["27", { path: "music/ct2_def.js", index: 0x4C, note: "", type: "se" }],
	["28", { path: "music/ct2_def.js", index: 0x4D, note: "", type: "se" }],
	["29", { path: "music/ct2_def.js", index: 0x4E, note: "", type: "se" }],
	["2A", { path: "music/ct2_def.js", index: 0x4F, note: "", type: "se" }],
	["2B", { path: "music/ct2_def.js", index: 0x50, note: "", type: "se" }],
	["2C", { path: "music/ct2_def.js", index: 0x51, note: "", type: "se" }],
	["2D", { path: "music/ct2_def.js", index: 0x52, note: "", type: "se" }],
	["2E", { path: "music/ct2_def.js", index: 0x53, note: "", type: "se" }],
	["2F", { path: "music/ct2_def.js", index: 0x54, note: "", type: "se" }],
	["30", { path: "music/ct2_def.js", index: 0x55, note: "", type: "se" }],
	//["31", { path: "music/ct2_def.js", index: 0xFF, note: "",type:"se" }],//空索引

	//以下是背景音乐
	["32", { path: "music/ct2_def.js", index: 0, note: "比赛5分钟倒计时音乐，最后关头（22）", type: "bgm" }],
	["33", { path: "music/ct2_def.js", index: 1, note: "输入密码时的音乐，穿越未来（23）", type: "bgm" }],
	["34", { path: "music/ct2_def.js", index: 2, note: "日本高中联赛音乐，决战日本（7-11关）（35）", type: "bgm" }],
	["35", { path: "music/ct2_def.js", index: 3, note: "巴西联赛音乐，巴西之战（1-5关）（34）", type: "bgm" }],
	["36", { path: "music/ct2_def.js", index: 4, note: "法国音乐，埃菲尔攻击（38）", type: "bgm" }],
	["37", { path: "music/ct2_def.js", index: 5, note: "东邦音乐，猛虎压境（31）", type: "bgm" }],
	["38", { path: "music/ct2_def.js", index: 6, note: "德国音乐，震撼火焰（32）", type: "bgm" }],
	["39", { path: "music/ct2_def.js", index: 7, note: "南葛音乐，南葛的反击（28）", type: "bgm" }],
	["3A", { path: "music/ct2_def.js", index: 8, note: "亚洲突围音乐（37）", type: "bgm" }],
	["3B", { path: "music/ct2_def.js", index: 9, note: "邀请赛（13至16关）音乐（36）", type: "bgm" }],
	["3C", { path: "music/ct2_def.js", index: 10, note: "圣保罗音乐，足球是朋友（27）", type: "bgm" }],
	["3D", { path: "music/ct2_def.js", index: 11, note: "阿根廷音乐，草原雄鹰（39）", type: "bgm" }],
	["3E", { path: "music/ct2_def.js", index: 12, note: "巴西音乐，神秘劲旅（33）", type: "bgm" }],
	["3F", { path: "music/ct2_def.js", index: 13, note: "全日本音乐，全日本进行曲（29）", type: "bgm" }],
	["40", { path: "music/ct2_def.js", index: 14, note: "弗拉门戈音乐，黄金之鹫（30）", type: "bgm" }],
	["41", { path: "music/ct2_def.js", index: 15, note: "我方进球音乐（24）", type: "bgm" }],
	["42", { path: "music/ct2_def.js", index: 16, note: "对方进球音乐（25）", type: "bgm" }],
	["43", { path: "music/ct2_def.js", index: 17, note: "犯规音乐（26）", type: "bgm" }],
	["44", { path: "music/ct2_def.js", index: 18, note: "爆笑三人转会议音乐（21）", type: "bgm" }],
	["45", { path: "music/ct2_def.js", index: 19, note: "爆笑三人转开始音乐（01）", type: "bgm" }],
	["46", { path: "music/ct2_def.js", index: 20, note: "翼单挑曼昂尼剧情音乐（06）", type: "bgm" }],
	["47", { path: "music/ct2_def.js", index: 21, note: "南葛战胜东邦剧情音乐（05）", type: "bgm" }],
	["48", { path: "music/ct2_def.js", index: 22, note: "爆机翼与早苗对话剧情音乐（11）", type: "bgm" }],
	["49", { path: "music/ct2_def.js", index: 23, note: "曼昂尼接住旋转射门后剧情音乐（12）", type: "bgm" }],
	["4A", { path: "music/ct2_def.js", index: 0xFF, note: "停止播放声音", type: "bgm" }],
	["4B", { path: "music/ct2_def.js", index: 24, note: "翼领悟飓风射门的剧情音乐，暴风雨中的试炼（13）", type: "bgm" }],
	["4C", { path: "music/ct2_def.js", index: 25, note: "最后一关对巴西会议音乐，最后的激励（14）", type: "bgm" }],
	["4D", { path: "music/ct2_def.js", index: 26, note: "爆机音乐之一，详细参考原曲（15）", type: "bgm" }],
	["4E", { path: "music/ct2_def.js", index: 27, note: "翼举奖杯的爆机音乐（16）", type: "bgm" }],
	["4F", { path: "music/ct2_def.js", index: 28, note: "爆机音乐，详细参考（17）", type: "bgm" }],
	["50", { path: "music/ct2_def.js", index: 29, note: "早苗最后告别剧情音乐（18）", type: "bgm" }],
	["51", { path: "music/ct2_def.js", index: 30, note: "隐藏剧情中与罗伯特对话（02）", type: "bgm" }],
	["52", { path: "music/ct2_def.js", index: 31, note: "翼领悟旋转倒挂的短促音乐（07）", type: "bgm" }],
	["53", { path: "music/ct2_def.js", index: 32, note: "卡洛斯第一次露面剧情音乐（04）", type: "bgm" }],
	["54", { path: "music/ct2_def.js", index: 33, note: "库因布拉神秘亮相剧情音乐（08）", type: "bgm" }],
	["55", { path: "music/ct2_def.js", index: 34, note: "会议音乐（03）", type: "bgm" }],
	["56", { path: "music/ct2_def.js", index: 35, note: "比赛输了的音乐（20）", type: "bgm" }],
	["57", { path: "music/ct2_def.js", index: 36, note: "翼为曼昂尼所震撼的剧情音乐（09）", type: "bgm" }],
	["58", { path: "music/ct2_def.js", index: 37, note: "片头音乐（00）", type: "bgm" }],
	["59", { path: "music/ct2_def.js", index: 38, note: "爆机音乐之一，详参（19）", type: "bgm" }],
	["5A", { path: "music/ct2_def.js", index: 39, note: "第一关赢后，卡洛斯的剧情音乐（10）", type: "bgm" }],

	//以下部分属于特殊音乐，自身播放时长比较短，但也属于背景音乐范围(部分为剧情音效)
	//["5B", { path: "music/ct2_def.js", index: 0xFF, note: "BUG音乐,也可以试听一下",type:"bgm" }],
	//["5C", { path: "music/ct2_def.js", index: 0, note: "无声音",type:"bgm" }],
	["5D", { path: "music/ct2_def.js", index: 0x56, note: "进球,网未穿56", type: "se" }],
	["5E", { path: "music/ct2_def.js", index: 0x57, note: "57", type: "se" }],
	["5F", { path: "music/ct2_def.js", index: 0x58, note: "58", type: "se" }],
	["60", { path: "music/ct2_def.js", index: 0x59, note: "进球,网未穿59", type: "se" }],
	["61", { path: "music/ct2_def.js", index: 0x5A, note: "进球,网射穿5A", type: "se" }],
	["62", { path: "music/ct2_def.js", index: 0x5B, note: "观众喝彩声5B", type: "se" }],
	["63", { path: "music/ct2_def.js", index: 0x5C, note: "球没进5C", type: "se" }],
	["64", { path: "music/ct2_def.js", index: 0x5D, note: "头球猛撞的一瞬间5D", type: "se" }],
	["65", { path: "music/ct2_def.js", index: 0x5E, note: "球爆裂的声音5E", type: "se" }],
	["66", { path: "music/ct2_def.js", index: 0x5F, note: "裁判的哨声5F", type: "se" }],
	["67", { path: "music/ct2_def.js", index: 0x60, note: "犯规哨声,后接26犯规音乐[这个在pm中没有]60", type: "bgm" }],
	["68", { path: "music/ct2_def.js", index: 0x61, note: "闪躲成功61", type: "se" }],
	["69", { path: "music/ct2_def.js", index: 0x62, note: "此起彼伏的喝彩声,比87略小声62", type: "se" }],
	["6A", { path: "music/ct2_def.js", index: 0x63, note: "机起飞的声音63", type: "se" }],
	["6B", { path: "music/ct2_def.js", index: 0x64, note: "剧情中施奈德火焰的前奏声音64", type: "se" }],
	["6C", { path: "music/ct2_def.js", index: 0x65, note: "对巴西赛前钟表到点的声音65", type: "se" }],
	["6D", { path: "music/ct2_def.js", index: 0x66, note: "这个声音既熟悉又陌生,故暂不解释66", type: "se" }],
	["6E", { path: "music/ct2_def.js", index: 0x67, note: "对巴西赛前钟表声音67", type: "se" }],
	["6F", { path: "music/ct2_def.js", index: 0x68, note: "人物升级的音乐68", type: "se" }],
	["70", { path: "music/ct2_def.js", index: 0x45, note: "下雨声45", type: "se" }],
	["71", { path: "music/ct2_def.js", index: 0x45, note: "下雨声45", type: "se" }],
]);











